### ISSUE TITLE
FlaskWTFDeprecationWarning - dependency updates required

### ISSUE THREAD

**Issue by shadowbq** [iadgov/WALKOFF#127]
```shell
  super(LoginForm, self).__init__(*args, **kwargs)
./home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/flask_security/forms.py:213: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
```

The deprecation warning lead to an update in flask, flask_wtf, Flask_SQLAlchemy, and flask_security

Flask >= 0.11.0
Flask_WTF >= 0.13.1, <1 (top side pinning)
Flask_Security == 3.0.0
Flask_SQLAlchemy >= 2.1, <3 (top side pinning)

**Comment by JustinTervala** [comment]
Resolved by removing all webforms
