### ISSUE TITLE
Pycodestyle / PEP8 review needed for PR and CI

### ISSUE THREAD

**Issue by shadowbq** [iadgov/WALKOFF#129]
A PEP8 review should be done on the code base on PR and .travis build automatically.

There should be a tool integration like: 
* codeclimate pep8
* coverall.io 
* codecov.io
* https://github.com/OrkoHunter/pep8speaks 

```
pycodestyle --statistics -qq ./
10      E101 indentation contains mixed spaces and tabs
194     E111 indentation is not a multiple of four
8       E114 indentation is not a multiple of four (comment)
20      E127 continuation line over-indented for visual indent
90      E128 continuation line under-indented for visual indent
1       E129 visually indented line with same indent as next logical line
21      E201 whitespace after '('
31      E202 whitespace before ')'
8       E203 whitespace before ':'
32      E221 multiple spaces before operator
11      E222 multiple spaces after operator
5       E231 missing whitespace after ','
17      E251 unexpected spaces around keyword / parameter equals
36      E261 at least two spaces before inline comment
1       E262 inline comment should start with '# '
6       E265 block comment should start with '# '
2       E266 too many leading '#' for block comment
1       E301 expected 1 blank line, found 0
52      E302 expected 2 blank lines, found 1
6       E303 too many blank lines (3)
13      E305 expected 2 blank lines after class or function definition, found 1
3       E306 expected 1 blank line before a nested definition, found 0
4       E401 multiple imports on one line
1       E402 module level import not at top of file
2997    E501 line too long (146 > 79 characters)
8       E703 statement ends with a semicolon
1       E721 do not compare types, use 'isinstance()'
12      E722 do not use bare except'
133     W191 indentation contains tabs
85      W291 trailing whitespace
26      W292 no newline at end of file
263     W293 blank line contains whitespace
23      W391 blank line at end of file
7       W602 deprecated form of raising exception
```

**Comment by shadowbq** [comment]
As an aside we can also watch [Cyclomatic Complexity](https://en.wikipedia.org/wiki/Cyclomatic_complexity) indexes with radon or xenon

https://github.com/rubik/radon

```
radon cc -nc ./
server/appdevice.py
    M 163:4 Device.edit_device - C
server/triggers.py
    M 97:4 Triggers.execute - C
core/validator.py
    F 320:0 validate_parameters - C
core/step.py
    M 329:4 Step.from_json - C
    M 97:4 Step._from_xml - C
    M 229:4 Step.to_xml - C
    M 301:4 Step.as_json - C
core/flags/count.py
    F 4:0 count - C
tests/test_metrics_server.py
    M 15:4 MetricsServerTest.test_convert_action_time_average - C
tests/test_step.py
    M 238:4 TestStep.__check_xml - C
tests/test_server.py
    M 139:4 TestConfiguration.test_set_configuration - C
    M 112:4 TestConfiguration.test_get_configuration - C
tests/util/flagsfilters/__init__.py
    F 17:0 count - C
apps/ARDrone/libardrone/demo.py
    F 36:0 main - D
apps/ARDrone/libardrone/arvideo.py
    F 281:0 inverse_dct - C
    F 416:0 get_mb - C
```

**Comment by iadgovuser11** [comment]
Have you used any of the tools before?  If so which one is your favorite?  Either way its a good idea we'll do some research into it.  Thanks!

**Comment by shadowbq** [comment]
I've used codeclimate, and coveralls in the past, but codecov.io is a newer hotness. They all provide 100% opensource project support. They all generally have a pip requirement and some .yml configuration file. 

I prefer Codeclimate. 

This SaaS tool measures the quality of project's code and returns a rate between 0.0 and 4.0. Its engine is based on:

Churn: approximately the number of times a file has changed in the last 90 days
Code complexity: Based on cyclomatic complexity (Radon/McCabe)
Duplication: Identical or duplicate code
Style: PEP8 etc.
Clarity: File and method's length, method's arguments
GIT Branch support: Yes

About the workflow: https://docs.codeclimate.com/v1.0/docs/workflow

Start here: https://docs.codeclimate.com/v1.0/docs/test-coverage-python
Aldo Read this: https://docs.codeclimate.com/v1.0/docs/travis-ci-python-test-coverage

Grading is based on engine configurations in `.codeclimate.yml`

If Code Climate does not detect a `.codeclimate.yml` Code Climate infers a configuration, a process which can be read about here: https://docs.codeclimate.com/v1.0/docs/default-analysis-configuration

Then:
https://docs.codeclimate.com/v1.0/docs/radon
https://docs.codeclimate.com/v1.0/docs/pep8

https://github.com/codeclimate/python-test-reporter
https://github.com/codeclimate/pep8

**Comment by JustinTervala** [comment]
We have added code climate configuration which checks for a wide variety of issues. We didn't incorporate this into Travis just yet, but we did add unit test coverage to Travis which ensures that the backend has > 81% code coverage.
