### ISSUE TITLE
Understanding what is returned from actions

### ISSUE THREAD

**Issue by MisoMadao** [iadgov/WALKOFF#157]
I tryed to configure a workflow with 2 actions, one after the other.
The actions are 
 - **get active hosts** from **nmap** app
 - **json select** from **utilities** app

I had many difficulties to understand what is returned from the first action, so I modified the **json select** action to print what is receiving as an input in order to understand.

Turns out that the actual received result is different from the result shown in the gui.
From the gui I see the result

![image](https://user-images.githubusercontent.com/14838054/30436144-c268177a-996b-11e7-8d51-051e204a7975.png)

But by printing the result in **json select** I can see that only the value of *the json*[result][result]

Is there a reason behind this difference? Is there a way to know what is returned from an action different from reading the code?

Many thanks

**Comment by JustinTervala** [comment]
Each action returns a **core.decorators.ActionResult** object which contains both the result of the action and the status code with which it exited. You can see how the object is constructed in the **core.decorators.action** decorator function which calls the **core.decorators.format_result** function. The results of the step are then sent in a slightly more nested JSON format using the blinker signal FunctionExecutionSuccess as a callback. The Server connects a function in server.blueprints.workflowresults to push these results in an SSE stream to the UI. What you're seeing is the UI just dumping that JSON to the screen. We should probably remove one level of 'result' from the JSON either on the backend or on the frontend.

**Comment by JustinTervala** [comment]
This has been fixed as of version 0.5.0
