### ISSUE TITLE
REST API docs

### ISSUE THREAD

**Issue by tbar001** [iadgov/WALKOFF#164]
Hello.

I had a look to the following link:
https://iadgov.github.io/WALKOFF/tutorials.html

It does not look updated. Is there any other reference for the API?
Thanks,

**Comment by coreyjrobins** [comment]
Hi tbar001,

That page is very out of date and is no longer linked to our github IO page. Here are the links to our [documentation landing page](https://iadgov.github.io/WALKOFF/documentation/build/index.html), [swagger API documentation](https://iadgov.github.io/WALKOFF/swagger/index.html), [code documentation](https://iadgov.github.io/WALKOFF/Sphinx_Docs/_build/html/index.html), and [tutorials](https://iadgov.github.io/WALKOFF/tutorials/build/index.html).

For reference, out github IO page can be found [here](https://iadgov.github.io/WALKOFF/).

**Comment by tbar001** [comment]
Hello.
Thanks for the links.
I had a look to the swagger API docs. It looks it is a bit outdated. For example, if I use it in order to compose the curl to execute a workflow, I obtain something like this:

`curl -X POST "http://127.0.0.1:5000/api/playbooks/basicWorkflowTest/workflows/helloWorldWorkflow/execute" -H  "accept: application/json" -H  "Authentication-Token:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2NsYWltcyI6eyJyb2xlcyI6WyJhZG1pbiJdfSwianRpIjoiN2NkOTlkODctMWE0Mi00OWNhLWIxOTctMzRiZTUyYzJlNDlhIiwiZXhwIjoxNTA2Njg3MjM0LCJmcmVzaCI6dHJ1ZSwiaWF0IjoxNTA2Njg2MzM0LCJ0eXBlIjoiYWNjZXNzIiwibmJmIjoxNTA2Njg2MzM0LCJpZGVudGl0eSI6ImFkbWluIn0.amZgF5m8s7ykPjyYjVb14Wgu_j15GN72Yj8AHhkYdkE"`

This is not working; a correct one is 

`curl -X POST "http://127.0.0.1:5000/api/playbooks/basicWorkflowTest/workflows/helloWorldWorkflow/execute" -H  "accept: application/json" -H  "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2NsYWltcyI6eyJyb2xlcyI6WyJhZG1pbiJdfSwianRpIjoiN2NkOTlkODctMWE0Mi00OWNhLWIxOTctMzRiZTUyYzJlNDlhIiwiZXhwIjoxNTA2Njg3MjM0LCJmcmVzaCI6dHJ1ZSwiaWF0IjoxNTA2Njg2MzM0LCJ0eXBlIjoiYWNjZXNzIiwibmJmIjoxNTA2Njg2MzM0LCJpZGVudGl0eSI6ImFkbWluIn0.amZgF5m8s7ykPjyYjVb14Wgu_j15GN72Yj8AHhkYdkE"`

So with "Authorization" instead of "Authentication-Token"

Thanks,

**Comment by JustinTervala** [comment]
We use JWT authentication, so you can use the header "Authorization: Bearer token.goes.here". Currently our documentation is autogenerated using Swagger UI which generates the docs from OpenAPI 2.0. OpenAPI 2.0 unfortunately does not support describing standard JWT security authorization schemes. OpenAPI 3.0 was recently released and does support this JWT schemes, but Swagger UI doesn't fully support OpenAPI 3.0 yet. We're watching their GitHub issue ([https://github.com/swagger-api/swagger-ui/issues/3705])for resolution, and when it is supported, we'll update accordingly. We'll put some additional documentation somewhere online in the meantime.
