### ISSUE TITLE
Issue with mainAPI.py

### ISSUE THREAD

**Issue by brianpb245** [iadgov/WALKOFF#18]
First Issue, the setup.py , initially Flask.ext.security and flask.ext.sqlalchemy was installed but the following were  needed and were not installed so we installed it manually 

                        'Flask_Principal >= 0.4.0',
                        'Flask_SQLAlchemy >= 2.1',
                        'Flask_Security >= 1.7.5',

When I try to run main.py , we are having this issue with mainAPI.py
```
[root@bn-r7-walkoff WALKOFF]# python main.py
/root/WALKOFF/apps/resources
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import api.mainAPI as webService
  File "/root/WALKOFF/api/mainAPI.py", line 153, in <module>
    security = Security(app, user_datastore)
  File "/usr/lib/python2.7/site-packages/Flask_Security-1.7.5-py2.7.egg/flask_security/core.py", line 401, in __init__
    self._state = self.init_app(app, datastore, **kwargs)
  File "/usr/lib/python2.7/site-packages/Flask_Security-1.7.5-py2.7.egg/flask_security/core.py", line 435, in init_app
    anonymous_user=anonymous_user)
  File "/usr/lib/python2.7/site-packages/Flask_Security-1.7.5-py2.7.egg/flask_security/core.py", line 268, in _get_state
    login_manager=_get_login_manager(app, anonymous_user),
  File "/usr/lib/python2.7/site-packages/Flask_Security-1.7.5-py2.7.egg/flask_security/core.py", line 226, in _get_login_manager
    lm.token_loader(_token_loader)
AttributeError: 'LoginManager' object has no attribute 'token_loader'

```

**Comment by iadgovuser11** [comment]
1.  The requirements are in setup.py did you notice any errors when it was retrieving the libraries?
2.  What os are you using so I can try to recreate?  

Just as a note we are currently revamping the platform under the Walkoff-2 branch which will replace the master branch when ready.

**Comment by brianpb245** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } So I found the error . We are running it on RHEL7, the issue was the setup.py was installing flask_login 0.4.0 when walkoff requires >= 0.3.2 and < 0.4.0 .
Will let you know if I run into any more issues . Do you know ETA of walkoff 2?


Sent from Yahoo Mail for iPhone


On Thursday, January 5, 2017, 11:56 AM, 5E54DE2C27691E3517B9BB76F7BCFA097E2ECEE316DF25ABFEC53799FE61F403 <notifications@github.com> wrote:

   
   - The requirements are in setup.py did you notice any errors when it was retrieving the libraries?
   - What os are you using so I can try to recreate?

Just as a note we are currently revamping the platform under the Walkoff-2 branch which will replace the master branch when ready.

**Comment by iadgovuser11** [comment]
Walkoff-2 should be ready within a few weeks.   Features and Unit Tests are being added on a continuous basis though.  Any questions/feedback/suggestions/contributions are welcome;  let us know how we can help.

**Comment by brianpb245** [comment]
Would you have an example of the Tanium display.py and index.html. Any help is appreciated!

**Comment by iadgovuser11** [comment]
Custom interfaces are optional in the apps.  We didn't create a custom interface for the Tanium app.   A good example of a custom interface for display.py and index.html would be in the linux shell app.   Display.py does any server side processing your app would need and index.html contains all of the web code.  Hope this helps!

**Comment by brianpb245** [comment]
Maybe I am understanding this wrong, once I have walkoff installed and running. the main.py for tanium is setup. How do I start using tanium from the web interface?

**Comment by iadgovuser11** [comment]
We've been working on a GUI to make the workflows however it has not yet been completed.  The best way to currently make the workflows is to edit the playbook.json file directly.   We have completed the gui interfaces for adding configuration information is there though.  The interfaces were originally envisioned for analytic apps and other types of apps that don't have their own standalone dashboard.
