### ISSUE TITLE
Cleared for use on NIPR?

### ISSUE THREAD

**Issue by Travis42** [iadgov/WALKOFF#190]
I know this question seems absurd, but believe me, some admin is going to want to know:

Is this free, open source software cleared for use on USAF NIPR, or anywhere else DOD does business?  Can we, the US government, use this thing the actual NSA made?  What proof do you have?

Thanks.  If you're a government employee, I'm sure you understand.

**Comment by iadgovuser11** [comment]
Not an absurd question at all, but this might be a better question for walkoff@nsa.gov if you wouldn't mind shooting us an email so that we can discuss more.
