### ISSUE TITLE
npm error while installing

### ISSUE THREAD

**Issue by nkh8212** [iadgov/WALKOFF#192]
`npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
npm WARN optional Skipping failed optional dependency /watchpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
npm WARN @ng-bootstrap/ng-bootstrap@1.0.0-alpha.17 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN @ng-bootstrap/ng-bootstrap@1.0.0-alpha.17 requires a peer of @angular/common@^2.0.0 but none was installed.
npm WARN @ng-bootstrap/ng-bootstrap@1.0.0-alpha.17 requires a peer of @angular/forms@^2.0.0 but none was installed.
npm WARN add-asset-html-webpack-plugin@2.1.3 requires a peer of html-webpack-plugin@^2.10.0 || ^3.0.4 but none was installed.
npm WARN sass-loader@6.0.7 requires a peer of node-sass@^4.0.0 but none was installed.
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none was installed.
npm ERR! Linux 4.13.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script 'node lib/post_install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the uglifyjs-webpack-plugin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/post_install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uglifyjs-webpack-plugin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls uglifyjs-webpack-plugin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/WALKOFF-0.7.4/walkoff/client/npm-debug.log

Compiling TypeScript Files...

> walkoff@ build /root/WALKOFF-0.7.4/walkoff/client
> npm run build:prod

> walkoff@ build:prod /root/WALKOFF-0.7.4/walkoff/client
> npm run clean:dist && npm run webpack -- --config webpack.prod.js  --progress --profile --bail

> walkoff@ clean:dist /root/WALKOFF-0.7.4/walkoff/client
> npm run rimraf -- dist

> walkoff@ rimraf /root/WALKOFF-0.7.4/walkoff/client
> rimraf "dist"

/usr/bin/env: 'node': No such file or directory

npm ERR! Linux 4.13.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "rimraf" "--" "dist"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! walkoff@ rimraf: `rimraf "dist"`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the walkoff@ rimraf script 'rimraf "dist"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the walkoff package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rimraf "dist"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs walkoff
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls walkoff
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/WALKOFF-0.7.4/walkoff/client/npm-debug.log

npm ERR! Linux 4.13.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "clean:dist"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! walkoff@ clean:dist: `npm run rimraf -- dist`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the walkoff@ clean:dist script 'npm run rimraf -- dist'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the walkoff package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run rimraf -- dist
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs walkoff
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls walkoff
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/WALKOFF-0.7.4/walkoff/client/npm-debug.log

npm ERR! Linux 4.13.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build:prod"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! walkoff@ build:prod: `npm run clean:dist && npm run webpack -- --config webpack.prod.js  --progress --profile --bail`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the walkoff@ build:prod script 'npm run clean:dist && npm run webpack -- --config webpack.prod.js  --progress --profile --bail'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the walkoff package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean:dist && npm run webpack -- --config webpack.prod.js  --progress --profile --bail
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs walkoff
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls walkoff
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/WALKOFF-0.7.4/walkoff/client/npm-debug.log

npm ERR! Linux 4.13.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! walkoff@ build: `npm run build:prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the walkoff@ build script 'npm run build:prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the walkoff package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs walkoff
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls walkoff
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/WALKOFF-0.7.4/walkoff/client/npm-debug.log
`
--------------------------------------------------------------------------------------------------------------

I try to install using "python setup_walkoff.py" on ubuntu 16.04.

But install failed with npm ERR.

How can I solve this?

**Comment by nkh8212** [comment]
Woops..... I solve this just type "ln -s /usr/bin/nodejs /usr/bin/node"....lol

**Comment by shadowbq** [comment]
`apt install nodejs-legacy` does the same thing. Its because the bin had an historical use in linux.
