### ISSUE TITLE
Create Windows PowerShell App

### ISSUE THREAD

**Issue by iadgovuser11** [iadgov/WALKOFF#8]
**Goal**
The app should be able to securely execute a PowerShell command and script on a remote host.  

**Functions**
executeCommand
The command should be a string argument passed in through the workflow

executeScript
The script should be a filename passed in through the workflow

**Comment by b-long** [comment]
Hi there,

Just stopping by to offer a recommendation: https://github.com/diyan/pywinrm .  I don't know much about PowerShell, but did at one point need to remote into a Windows system and invoke some regular Windows commands.  

The pywinrm README describes invoking Powershell : https://github.com/diyan/pywinrm#run-powershell-script-on-remote-host

You can find my rudimentary usage of pywinrm here : https://github.com/b-long/WinRMTest .

Good luck!

**Comment by iadgovuser11** [comment]
Awesome we will look into this, thanks! 

Let us know if you need any assistance, have any feedback, or have any good automation use cases.  

Thanks,
-The Walkoff Team
